services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    environment:
      - SOURCE_COMMIT
      - SERVICE_FQDN_FRONTEND
      - SERVICE_URL_FRONTEND
    restart: unless-stopped
