services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    expose:
      - "80"
    environment:
      - COOLIFY_URL
      - COOLIFY_FQDN
      - COOLIFY_BRANCH
      - SOURCE_COMMIT
      - COOLIFY_RESOURCE_UUID
    restart: unless-stopped
